# Generated by Django 3.2.25 on 2026-08-09 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_profile_torn_id'), ('users', '0003_auto_20200721_1854'), ('users', '0004_auto_20200726_1505'), ('users', '0005_auto_20200731_1911'), ('users', '0006_profile_api_key'), ('users', '0007_profile_name'), ('users', '0008_auto_20200817_0043'), ('users', '0009_settings'), ('users', '0010_auto_20200817_1830'), ('users', '0011_auto_20200820_2055'), ('users', '0012_auto_20200820_2157'), ('users', '0013_auto_20200820_2321'), ('users', '0014_auto_20200820_2350'), ('users', '0015_auto_20200823_1537'), ('users', '0016_auto_20200824_1540'), ('users', '0017_settings_job_post_start_date'), ('users', '0018_profile_work_stats_total'), ('users', '0019_auto_20201109_1617'), ('users', '0020_settings_selling_company'), ('users', '0021_auto_20201110_1443'), ('users', '0022_auto_20201110_1452'), ('users', '0023_auto_20210309_1948'), ('users', '0024_settings_service_list_description'), ('users', '0025_profile_active_trader'), ('users', '0026_settings_trade_enable_sets'), ('users', '0027_profile_hidden_categories'), ('users', '0028_profile_order_categories'), ('users', '0029_settings_trade_global_fee'), ('users', '0030_auto_20250310_0917'), ('users', '0031_alter_profile_api_key'), ('users', '0032_profile_monthly_trades'), ('users', '0033_alter_settings_receipt_paste_text'), ('users', '0034_profile_on_vacation')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('torn_id', models.CharField(max_length=250, null=True, unique=True)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_status', models.CharField(max_length=250, null=True)),
                ('last_active', models.DateTimeField(null=True)),
                ('work_stats_end', models.IntegerField(null=True)),
                ('work_stats_int', models.IntegerField(null=True)),
                ('work_stats_man', models.IntegerField(null=True)),
                ('work_stats_total', models.IntegerField(null=True)),
                ('te_plus_days', models.IntegerField(null=True)),
                ('te_plus_status', models.BooleanField(default=False)),
                ('active_trader', models.BooleanField(default=False)),
                ('hidden_categories', models.JSONField(default=dict)),
                ('order_categories', models.JSONField(default=list)),
                ('monthly_trades', models.IntegerField(null=True)),
                ('on_vacation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_list_description', models.CharField(blank=True, max_length=500, null=True)),
                ('link_to_forum_post', models.CharField(blank=True, max_length=250, null=True)),
                ('receipt_paste_text', models.TextField(blank=True, max_length=500, null=True)),
                ('tutorial', models.BooleanField(default=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.profile')),
                ('losses_message', models.CharField(blank=True, max_length=140, null=True)),
                ('revives_message', models.CharField(blank=True, max_length=140, null=True)),
                ('selling_losses', models.BooleanField(default=False)),
                ('selling_revives', models.BooleanField(default=False)),
                ('job_message', models.CharField(blank=True, max_length=140, null=True)),
                ('job_seeking', models.BooleanField(default=False)),
                ('job_post_start_date', models.DateTimeField(auto_now_add=True)),
                ('selling_company', models.BooleanField(default=False)),
                ('selling_company_asking_price', models.BigIntegerField(default=0)),
                ('selling_company_description', models.CharField(blank=True, max_length=140, null=True)),
                ('selling_company_price_negotiable', models.BooleanField(default=False)),
                ('company_looking_to_hire', models.BooleanField(default=False)),
                ('company_looking_to_hire_message', models.CharField(blank=True, max_length=140, null=True)),
                ('service_list_description', models.CharField(blank=True, max_length=500, null=True)),
                ('trade_enable_sets', models.BooleanField(default=True)),
                ('trade_global_fee', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
            ],
        ),
    ]
