# Generated by Django 3.2.25 on 2026-08-09 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('torn_id', models.CharField(max_length=250, null=True, unique=True)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_status', models.CharField(max_length=250, null=True)),
                ('last_active', models.DateTimeField(null=True)),
                ('work_stats_end', models.IntegerField(null=True)),
                ('work_stats_int', models.IntegerField(null=True)),
                ('work_stats_man', models.IntegerField(null=True)),
                ('work_stats_total', models.IntegerField(null=True)),
                ('te_plus_days', models.IntegerField(null=True)),
                ('te_plus_status', models.BooleanField(default=False)),
                ('active_trader', models.BooleanField(default=False)),
                ('hidden_categories', models.JSONField(default=dict)),
                ('order_categories', models.JSONField(default=list)),
                ('monthly_trades', models.IntegerField(null=True)),
                ('on_vacation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_list_description', models.CharField(blank=True, max_length=500, null=True)),
                ('link_to_forum_post', models.CharField(blank=True, max_length=250, null=True)),
                ('receipt_paste_text', models.TextField(blank=True, max_length=500, null=True)),
                ('tutorial', models.BooleanField(default=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.profile')),
                ('losses_message', models.CharField(blank=True, max_length=140, null=True)),
                ('revives_message', models.CharField(blank=True, max_length=140, null=True)),
                ('selling_losses', models.BooleanField(default=False)),
                ('selling_revives', models.BooleanField(default=False)),
                ('job_message', models.CharField(blank=True, max_length=140, null=True)),
                ('job_seeking', models.BooleanField(default=False)),
                ('job_post_start_date', models.DateTimeField(auto_now_add=True)),
                ('selling_company', models.BooleanField(default=False)),
                ('selling_company_asking_price', models.BigIntegerField(default=0)),
                ('selling_company_description', models.CharField(blank=True, max_length=140, null=True)),
                ('selling_company_price_negotiable', models.BooleanField(default=False)),
                ('company_looking_to_hire', models.BooleanField(default=False)),
                ('company_looking_to_hire_message', models.CharField(blank=True, max_length=140, null=True)),
                ('service_list_description', models.CharField(blank=True, max_length=500, null=True)),
                ('trade_enable_sets', models.BooleanField(default=True)),
                ('trade_global_fee', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
            ],
        ),
    ]
