# Generated by Django 3.0.8 on 2020-07-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='torn_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
