# Generated by Django 3.0.8 on 2020-07-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_torn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='torn_id',
            field=models.IntegerField(null=True),
        ),
    ]
