# Generated by Django 3.0.8 on 2020-07-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200721_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
