# Generated by Django 3.0.8 on 2020-07-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200726_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='torn_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
