# Generated by Django 3.0.8 on 2020-08-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200731_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
