# Generated by Django 3.0.8 on 2020-08-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='tester', max_length=500),
            preserve_default=False,
        ),
    ]
