# Generated by Django 3.0.8 on 2020-08-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200817_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_list_description', models.TextField(blank=True, null=True)),
                ('link_to_forum_post', models.CharField(max_length=1024, null=True)),
                ('receipt_paste_text', models.TextField(blank=True, null=True)),
                ('tutorial', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
