# Generated by Django 3.0.8 on 2020-08-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200817_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='losses_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='revives_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='selling_losses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='selling_revives',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='trade_list_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
