# Generated by Django 3.0.8 on 2020-08-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200820_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_status',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(null=True),
        ),
    ]
