# Generated by Django 3.0.8 on 2020-08-20 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200820_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.Profile'),
        ),
    ]
