# Generated by Django 3.0.8 on 2020-08-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200820_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='losses_message',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='revives_message',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
