# Generated by Django 3.0.8 on 2020-08-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200820_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='torn_id',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
