# Generated by Django 3.0.8 on 2020-08-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200823_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_stats_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_stats_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_stats_man',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='job_message',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='job_seeking',
            field=models.BooleanField(default=False),
        ),
    ]
