# Generated by Django 3.0.8 on 2020-11-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_settings_selling_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='selling_company_asking_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='selling_company_description',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='selling_company_price_negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
