# Generated by Django 3.0.8 on 2020-11-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20201110_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='selling_company_asking_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
