# Generated by Django 3.0.8 on 2021-03-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20201110_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='company_looking_to_hire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='company_looking_to_hire_message',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
