# Generated by Django 3.0.8 on 2024-10-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210309_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='service_list_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
