# Generated by Django 3.0.8 on 2024-10-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_settings_service_list_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_trader',
            field=models.BooleanField(default=False),
        ),
    ]
