# Generated by Django 3.0.12 on 2025-01-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_profile_active_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='trade_enable_sets',
            field=models.BooleanField(default=True),
        ),
    ]
