# Generated by Django 3.0.12 on 2025-01-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_profile_active_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='rounding_option',
            field=models.CharField(choices=[('none', 'No Rounding'), ('up', 'Round to Nearest 100 Up'), ('down', 'Round to Nearest 100 Down')], default='none', max_length=10, verbose_name='Rounding Option'),
        ),
    ]
