# Generated by Django 3.0.12 on 2025-02-02 22:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_settings_trade_enable_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hidden_categories',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
