# Generated by Django 3.0.12 on 2025-02-05 00:54

from django.db.models import JSONField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_profile_hidden_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order_categories',
            field=JSONField(default=list),
        ),
    ]
