# Generated by Django 3.0.12 on 2025-02-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_profile_order_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='trade_global_fee',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
