# Generated by Django 3.2.25 on 2026-03-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_profile_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_trades',
            field=models.IntegerField(null=True),
        ),
    ]
