# Generated by Django 3.2.25 on 2026-03-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_profile_monthly_trades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='receipt_paste_text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
