# Generated by Django 3.2.25 on 2026-07-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_settings_receipt_paste_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='on_vacation',
            field=models.BooleanField(default=False),
        ),
    ]
