# Generated by Django 4.2.30 on 2026-08-10 15:54

from django.db import migrations

# Discount must stay within the range accepted elsewhere (main/api.py's
# modify_listing), so a bake-in target outside it can't be represented.
MAX_DISCOUNT = 100


def bake_in_global_fee(apps, schema_editor):
    """
    Folds each trader's about-to-be-removed trade_global_fee into the
    `discount` of their discount-based Listings, so `effective_price`
    (min(price, discount-off-TE_value)) is unchanged once the field is gone.

    Runs against the historical model state, i.e. before the RemoveField
    operation below drops the column -- trade_global_fee is still readable
    here regardless of what main/models.py or users/models.py look like by
    the time this migration is actually applied.
    """
    Listing = apps.get_model('main', 'Listing')

    qs = (
        Listing.objects
        .filter(discount__isnull=False, owner__settings__trade_global_fee__gt=0)
        .exclude(item__item_id__gt=9000)
        .select_related('owner__settings', 'item')
    )
    for listing in qs:
        global_fee = listing.owner.settings.trade_global_fee
        new_discount = listing.discount + global_fee
        if new_discount > MAX_DISCOUNT:
            # Only possible when discount was already >95, since fee maxes at 5.
            # Leave these untouched rather than clamp -- effective_price will
            # shift slightly, but representing the true baked-in discount isn't
            # possible within the accepted range.
            continue

        discount_fraction = (100.0 - new_discount) / 100.0
        discount_price = discount_fraction * round(listing.item.TE_value or 0)
        if listing.price is None:
            effective_price = round(discount_price or 0)
        else:
            effective_price = round(min(discount_price, listing.price))

        listing.discount = new_discount
        listing.effective_price = effective_price
        listing.save(update_fields=['discount', 'effective_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed_0034_profile_on_vacation'),
        ('main', '0059_receipt_management_changelog_entry'),
    ]

    operations = [
        migrations.RunPython(bake_in_global_fee, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='settings',
            name='trade_global_fee',
        ),
    ]
