# Generated by Django 4.2.30 on 2026-09-07 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0036_backfill_forum_link_full_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroupStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('group_name', models.CharField(max_length=100)),
                ('group_key', models.CharField(blank=True, default='', max_length=100)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('score', models.BigIntegerField(blank=True, null=True)),
                ('lives', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', '-score'],
                'unique_together': {('event_key', 'year', 'group_name')},
            },
        ),
        migrations.CreateModel(
            name='EventTraderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('group_discount_pct', models.IntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_trader_settings', to='users.profile')),
            ],
            options={
                'unique_together': {('profile', 'event_key', 'year')},
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('group_name', models.CharField(blank=True, default='', max_length=100)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('score', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='users.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['event_key', 'year', 'group_name'], name='events_even_event_k_c9b18f_idx')],
                'unique_together': {('profile', 'event_key', 'year')},
            },
        ),
    ]
