# Generated by Django 4.2.30 on 2026-09-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_backfill_forum_link_full_url'),
        ('main', '0061_listing_event_discount_pct'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('raw_hash', models.CharField(max_length=40)),
                ('line_count', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TreasuryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('requester_torn_id', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partially fulfilled'), ('fulfilled', 'Fulfilled'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_requests', to='users.profile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='captain_proof_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='TreasuryRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity_requested', models.IntegerField(default=1)),
                ('quantity_fulfilled', models.IntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.item')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='events.treasuryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TreasuryLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('in', 'Donation in'), ('out', 'Payout out')], max_length=3)),
                ('counterparty_name', models.CharField(blank=True, default='', max_length=100)),
                ('counterparty_torn_id', models.CharField(blank=True, default='', max_length=20)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_cash', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_value', models.BigIntegerField(default=0)),
                ('total_value', models.BigIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('helper_trade', 'TE Helper trade'), ('log_paste', 'Torn log paste'), ('manual', 'Manual entry')], default='manual', max_length=20)),
                ('source_ref', models.CharField(blank=True, default='', max_length=64)),
                ('line_fingerprint', models.CharField(blank=True, default='', max_length=40)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='events.treasuryimportbatch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.profile')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.item')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='events.treasuryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('captain', 'Captain'), ('vice_captain', 'Vice-captain'), ('treasurer', 'Treasurer'), ('team_trader', 'Team trader'), ('member', 'Member')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_roles', to='users.profile')),
            ],
        ),
        migrations.AddIndex(
            model_name='treasuryrequest',
            index=models.Index(fields=['event_key', 'year', 'team_name', 'status'], name='events_trea_event_k_0cf9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryledgerentry',
            index=models.Index(fields=['event_key', 'year', 'team_name'], name='events_trea_event_k_78e08f_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryledgerentry',
            index=models.Index(fields=['team_name', 'direction'], name='events_trea_team_na_de5307_idx'),
        ),
        migrations.AddIndex(
            model_name='treasuryledgerentry',
            index=models.Index(fields=['team_name', 'counterparty_name'], name='events_trea_team_na_7f9c52_idx'),
        ),
        migrations.AddConstraint(
            model_name='treasuryledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('line_fingerprint__gt', '')), fields=('event_key', 'year', 'line_fingerprint'), name='uniq_treasury_line_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='treasuryimportbatch',
            index=models.Index(fields=['event_key', 'year', 'team_name'], name='events_trea_event_k_cf15f9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrole',
            index=models.Index(fields=['event_key', 'year', 'team_name', 'role'], name='events_even_event_k_ba5a3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventrole',
            unique_together={('profile', 'event_key', 'year', 'role')},
        ),
    ]
