# Generated by Django 3.2.25 on 2026-08-09 13:39

import django.contrib.postgres.operations
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import main.models
from django.utils.crypto import get_random_string



def gen_urls(apps, schema_editor):
    MyModel = apps.get_model('main', 'TradeReceipt')
    for row in MyModel.objects.all():
        row.receipt_url_string = get_random_string(10)
        row.save(update_fields=['receipt_url_string'])


def default_services():
    return [
        {'name': 'Bookie Tips', 'description': '', 'category': 'Torn feature'},
        {'name': 'Racing Assistant', 'description': '', 'category': 'Torn feature'},
        {'name': 'Reviving', 'description': '', 'category': 'Torn feature'},
        {'name': 'Stocks Advice', 'description': '', 'category': 'Torn feature'},

        {'name': 'View anonymous bounties', 'description': '', 'category': 'Company specials'},
        {'name': 'Hack a company\'s bank account', 'description': '', 'category': 'Company specials'},
        {'name': 'Company productivity boost', 'description': '', 'category': 'Company specials'},
        {'name': 'Flight Delay', 'description': '', 'category': 'Company specials'},
        {'name': 'See Friends & Enemies', 'description': '', 'category': 'Company specials'},
        {'name': 'View Money on Hand', 'description': '', 'category': 'Company specials'},
        {'name': 'View Stats & Money', 'description': '', 'category': 'Company specials'},
        {'name': 'True Level Reveal', 'description': '', 'category': 'Company specials'},
        {'name': 'Stat Spies', 'description': '', 'category': 'Company specials'},
        {'name': 'Creating Discord Bots', 'description': '', 'category': 'Software'},

        {'name': 'General Coding', 'description': '', 'category': 'Software'},
        {'name': 'Scripting', 'description': '', 'category': 'Software'},
        {'name': 'Discord Administration', 'description': '', 'category': 'Software'},
        {'name': 'Custom Spreadsheets', 'description': '', 'category': 'Software'},

        {'name': 'Selling Escapes', 'description': '', 'category': 'Attacking'},
        {'name': 'Selling Losses', 'description': '', 'category': 'Attacking'},
        {'name': 'Selling Stalemates', 'description': '', 'category': 'Attacking'},
        {'name': 'Mercenary', 'description': '', 'category': 'Attacking'},

        {'name': 'Graphics', 'description': '', 'category': 'Custom services'},
        {'name': 'RW Armor', 'description': '', 'category': 'Custom services'},
        {'name': 'RW Weapons', 'description': '', 'category': 'Custom services'},

        {'name': 'Other', 'description': '', 'category': 'Other'},
    ]


def add_default_services(apps, schema_editor):
    Service = apps.get_model('main', 'Service')
    data = default_services()
    for service_data in data:
        Service.objects.create(**service_data)


def remove_default_services(apps, schema_editor):
    Service = apps.get_model('main', 'Service')
    service_names = [service['name'] for service in default_services()]
    services_to_delete = Service.objects.filter(name__in=service_names)
    services_to_delete.delete()


def _calculate(listing):
    import numpy as np

    price = listing.price
    discount = listing.discount

    if discount is None and price is None:
        return None

    if discount is None and price is not None:
        return round(price)

    try:
        global_fee = listing.owner.settings.trade_global_fee or 0
    except Exception:
        global_fee = 0

    try:
        item_id = listing.item.item_id
    except Exception:
        item_id = 0
    if item_id and item_id > 9000:
        global_fee = 0

    total_discount = (discount or 0) + global_fee
    discount_fraction = (100.0 - total_discount) / 100.0
    discount_price = discount_fraction * round(listing.item.TE_value or 0)

    if price is None:
        return round(discount_price or 0)

    return round(np.nan_to_num(np.nanmin([discount_price, price])))


def populate_effective_price(apps, schema_editor):
    Listing = apps.get_model('main', 'Listing')
    for listing in Listing.objects.select_related('owner__settings', 'item').iterator():
        listing.effective_price = _calculate(listing)
        try:
            listing.save(update_fields=['effective_price'])
        except Exception:
            pass


CHANGELOG_TEXT = (
    "TE Market Value now also factors in bazaar averages (in addition to Torn's "
    "market value and our own item-market price), giving a more accurate lowest-of-three "
    "estimate. Existing discount-based prices were automatically rebalanced so your "
    "effective price didn't change -- but since bazaar averages are usually the lowest "
    "of the three, it's worth reviewing your profit margins on the edit prices page."
)


def create_changelog_entry(apps, schema_editor):
    ChangeLog = apps.get_model('main', 'ChangeLog')
    ChangeLog.objects.get_or_create(description=CHANGELOG_TEXT)


def remove_changelog_entry(apps, schema_editor):
    ChangeLog = apps.get_model('main', 'ChangeLog')
    ChangeLog.objects.filter(description=CHANGELOG_TEXT).delete()


class Migration(migrations.Migration):

    atomic = False

    replaces = [('main', '0001_initial'), ('main', '0002_auto_20200719_1417'), ('main', '0003_listing'), ('main', '0004_listing_price'), ('main', '0005_auto_20200719_2100'), ('main', '0006_auto_20200719_2123'), ('main', '0007_listing_discount'), ('main', '0008_item_last_updated'), ('main', '0009_auto_20200722_2211'), ('main', '0010_item_last_updated'), ('main', '0011_listing_effective_price'), ('main', '0012_itemtrade_tradereceipt'), ('main', '0013_auto_20200727_2315'), ('main', '0014_auto_20200728_0009'), ('main', '0015_itemtrade_market_value_at_save'), ('main', '0016_settings'), ('main', '0017_auto_20200817_0038'), ('main', '0018_changelog'), ('main', '0019_settings_tutorial'), ('main', '0020_delete_settings'), ('main', '0021_auto_20200817_1836'), ('main', '0022_auto_20200819_1544'), ('main', '0023_tradereceipt_receipt_url_string'), ('main', '0024_auto_20200823_1425'), ('main', '0025_auto_20200823_1425'), ('main', '0026_auto_20200823_2239'), ('main', '0027_auto_20200823_2300'), ('main', '0028_auto_20200825_2052'), ('main', '0029_auto_20200825_2207'), ('main', '0030_company'), ('main', '0031_auto_20201110_1443'), ('main', '0032_company_company_id'), ('main', '0033_company_looking_to_hire'), ('main', '0034_auto_20210309_2005'), ('main', '0035_remove_listing_effective_price'), ('main', '0036_service_services'), ('main', '0037_auto_20241013_2307'), ('main', '0038_auto_20241114_0015'), ('main', '0039_listing_hidden'), ('main', '0040_auto_20250310_2044'), ('main', '0041_alter_itemvariation_price'), ('main', '0042_alter_itemvariation_owner'), ('main', '0043_auto_20250311_2121'), ('main', '0044_itemvariationbonuses_description'), ('main', '0045_itemvariation_market_type'), ('main', '0046_job_joblog_schedule'), ('main', '0047_schedule_unique'), ('main', '0048_listing_effective_price'), ('main', '0049_populate_effective_price'), ('main', '0050_populate_effective_price'), ('main', '0051_listing_hidden_reasons'), ('main', '0052_add_trade_id_to_receipt'), ('main', '0053_item_bazaar_average'), ('main', '0054_item_item_id_unique_constraint'), ('main', '0055_bazaar_mv_changelog_entry'), ('main', '0056_receipt_search_indexes'), ('main', '0057_receipt_seller_upper_index'), ('main', '0058_receipt_total_amount')]

    dependencies = [
        ('users', '0030_auto_20250310_0917'),
        ('users', '0023_auto_20210309_1948'),
        ('users', '0031_alter_profile_api_key'),
        ('users', '0001_initial'),
        ('users', '0020_settings_selling_company'),
        ('users', '0007_profile_name'),
        ('users', '0004_auto_20200726_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('requirement', models.TextField()),
                ('item_type', models.CharField(max_length=250)),
                ('weapon_type', models.CharField(max_length=250, null=True)),
                ('buy_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('market_value', models.IntegerField()),
                ('circulation', models.IntegerField()),
                ('image_url', models.CharField(max_length=250)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('price', models.IntegerField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('effective_price', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('owner', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ItemTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('quantity', models.IntegerField()),
                ('seller', models.CharField(max_length=250, null=True)),
                ('market_value_at_save', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TradeReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items_trades', models.ManyToManyField(to='main.ItemTrade')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('seller', models.CharField(max_length=250, null=True)),
                ('receipt_url_string', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RunPython(
            code=gen_urls,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='tradereceipt',
            name='receipt_url_string',
            field=models.CharField(default=main.models.generate_url_string, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='buy_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='circulation',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='market_value',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='itemtrade',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtrade',
            name='seller',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='TE_value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
        migrations.RenameField(
            model_name='itemtrade',
            old_name='market_value_at_save',
            new_name='TE_value_at_save',
        ),
        migrations.AlterField(
            model_name='itemtrade',
            name='TE_value_at_save',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('company_type', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
                ('days_old', models.IntegerField()),
                ('weekly_income', models.BigIntegerField()),
                ('weekly_customers', models.BigIntegerField()),
                ('employees_hired', models.IntegerField()),
                ('employees_capacity', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('efficiency', models.IntegerField()),
                ('average_employee_tenure', models.IntegerField()),
                ('average_employee_efficiency', models.IntegerField()),
                ('negotiable', models.BooleanField(default=True)),
                ('asking_price', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.IntegerField()),
                ('company_looking_to_hire_message', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='effective_price',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=250)),
                ('category', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_price', models.BigIntegerField(null=True)),
                ('barter_price', models.TextField(max_length=20)),
                ('offer_description', models.TextField(max_length=250)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service')),
            ],
        ),
        migrations.RunPython(
            code=add_default_services,
            reverse_code=remove_default_services,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='services',
            unique_together={('owner', 'service')},
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Torn Feature', 'Tornfeature'), ('Company specials', 'Company'), ('Software', 'Software'), ('Atacking', 'Attacking'), ('Other', 'Other')], max_length=250),
        ),
        migrations.AddField(
            model_name='listing',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ItemBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('damage', models.FloatField(null=True)),
                ('armor', models.FloatField(null=True)),
                ('quality', models.FloatField()),
                ('rarity', models.CharField(max_length=15, null=True)),
                ('price', models.IntegerField(null=True)),
                ('is_saleable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(null=True)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='changelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemtrade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tradereceipt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ItemVariationBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('type', models.CharField(max_length=250)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.itembonus')),
                ('item_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.itemvariation')),
            ],
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
        migrations.CreateModel(
            name='ItemBBValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
        ),
        migrations.AlterField(
            model_name='itemvariation',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='itemvariation',
            name='uid',
            field=models.BigIntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='itemvariation',
            constraint=models.UniqueConstraint(condition=models.Q(('uid__isnull', False)), fields=('uid',), name='unique_non_null_uid'),
        ),
        migrations.AddField(
            model_name='itemvariationbonuses',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='market_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=250)),
                ('queue', models.CharField(max_length=250)),
                ('payload', models.JSONField(null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('reserved_at', models.DateTimeField(null=True)),
                ('available_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=30)),
                ('message', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=250)),
                ('payload', models.JSONField(null=True)),
                ('run_at', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('runnable', models.BooleanField(default=True)),
                ('last_ran_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='effective_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE main_listing ALTER COLUMN effective_price TYPE bigint',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(
            code=populate_effective_price,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='listing',
            name='hidden_by_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='hidden_by_inactivity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='hidden_by_vacation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradereceipt',
            name='trade_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='bazaar_average',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='bazaar_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('item_id__isnull', False)), fields=('item_id',), name='unique_non_null_item_id'),
        ),
        migrations.RunPython(
            code=create_changelog_entry,
            reverse_code=remove_changelog_entry,
        ),
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='itemtrade',
            index=models.Index(fields=['owner'], name='itemtrade_owner_idx'),
        ),
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='itemtrade',
            index=models.Index(fields=['item'], name='itemtrade_item_idx'),
        ),
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='tradereceipt',
            index=models.Index(fields=['owner', 'seller'], name='tradereceipt_owner_seller_idx'),
        ),
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='tradereceipt',
            index=models.Index(fields=['seller'], name='tradereceipt_seller_idx'),
        ),
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='tradereceipt',
            index=models.Index(fields=['created_at'], name='tradereceipt_created_at_idx'),
        ),
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='tradereceipt',
            index=models.Index(fields=['trade_id'], name='tradereceipt_trade_id_idx'),
        ),
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='tradereceipt',
            index=models.Index(django.db.models.functions.text.Upper('seller'), name='tradereceipt_seller_upper_idx'),
        ),
        migrations.AddField(
            model_name='tradereceipt',
            name='total_amount',
            field=models.BigIntegerField(null=True),
        ),
        django.contrib.postgres.operations.AddIndexConcurrently(
            model_name='tradereceipt',
            index=models.Index(fields=['total_amount'], name='tradereceipt_total_amount_idx'),
        ),
    ]
