# Generated by Django 3.0.8 on 2020-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('requirement', models.TextField()),
                ('item_type', models.CharField(max_length=250)),
                ('weapon_type', models.CharField(max_length=250)),
                ('buy_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('market_value', models.IntegerField()),
                ('circulation', models.IntegerField()),
                ('image_url', models.CharField(max_length=250)),
            ],
        ),
    ]
