# Generated by Django 3.0.8 on 2020-07-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
