# Generated by Django 3.0.8 on 2020-07-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0004_listing_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listing',
            unique_together={('Owner', 'Item')},
        ),
    ]
