# Generated by Django 3.0.8 on 2020-07-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0005_auto_20200719_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Price',
            new_name='price',
        ),
        migrations.AlterUniqueTogether(
            name='listing',
            unique_together={('owner', 'item')},
        ),
    ]
