# Generated by Django 3.0.8 on 2020-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_listing_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
