# Generated by Django 3.0.8 on 2020-07-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_item_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='effective_price',
            field=models.IntegerField(null=True),
        ),
    ]
