# Generated by Django 3.0.8 on 2020-07-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_itemtrade_tradereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtrade',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemtrade',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
