# Generated by Django 3.0.8 on 2020-07-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200727_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtrade',
            name='buyer',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tradereceipt',
            name='buyer',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
