# Generated by Django 3.0.8 on 2020-08-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200728_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtrade',
            name='market_value_at_save',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
