# Generated by Django 3.0.8 on 2020-08-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='receipt_paste_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='link_to_forum_post',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='trade_list_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
