# Generated by Django 3.0.8 on 2020-08-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='tutorial',
            field=models.BooleanField(default=True),
        ),
    ]
