# Generated by Django 3.0.8 on 2020-08-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_settings_tutorial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
