# Generated by Django 3.0.8 on 2020-08-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_delete_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtrade',
            old_name='buyer',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='tradereceipt',
            old_name='buyer',
            new_name='seller',
        ),
    ]
