# Generated by Django 3.0.8 on 2020-08-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200817_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='discount',
            field=models.FloatField(null=True),
        ),
    ]
