# Generated by Django 3.0.8 on 2020-08-23 13:24

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200819_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradereceipt',
            name='receipt_url_string',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
