# Generated by Django 3.0.8 on 2020-08-23 13:25

from django.db import migrations
from django.utils.crypto import get_random_string


def gen_urls(apps, schema_editor):
    MyModel = apps.get_model('main', 'TradeReceipt')
    for row in MyModel.objects.all():
        row.receipt_url_string = get_random_string(10)
        row.save(update_fields=['receipt_url_string'])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_tradereceipt_receipt_url_string'),
    ]

    operations = [
	    # omit reverse_code=... if you don't want the migration to be reversible.
	    migrations.RunPython(gen_urls, reverse_code=migrations.RunPython.noop),
	]
