# Generated by Django 3.0.8 on 2020-08-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200823_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buy_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='circulation',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='market_value',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='itemtrade',
            name='market_value_at_save',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='itemtrade',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='effective_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
    ]
