# Generated by Django 3.0.8 on 2020-08-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200823_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtrade',
            name='seller',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
