# Generated by Django 3.0.8 on 2020-08-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200823_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='TE_value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
    ]
