# Generated by Django 3.0.8 on 2020-08-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200825_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtrade',
            old_name='market_value_at_save',
            new_name='TE_value_at_save',
        ),
    ]
