# Generated by Django 3.0.8 on 2020-11-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_settings_selling_company'),
        ('main', '0029_auto_20200825_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('company_type', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
                ('days_old', models.IntegerField()),
                ('weekly_income', models.BigIntegerField()),
                ('weekly_customers', models.BigIntegerField()),
                ('employees_hired', models.IntegerField()),
                ('employees_capacity', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('efficiency', models.IntegerField()),
                ('average_employee_tenure', models.IntegerField()),
                ('average_employee_efficiency', models.IntegerField()),
                ('negotiable', models.BooleanField(default=True)),
                ('asking_price', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
