# Generated by Django 3.0.8 on 2020-11-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20201110_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(default=242),
            preserve_default=False,
        ),
    ]
