# Generated by Django 3.0.8 on 2021-03-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_company_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='looking_to_hire',
            field=models.BooleanField(default=False),
        ),
    ]
