# Generated by Django 3.0.8 on 2021-03-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_company_looking_to_hire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='looking_to_hire',
        ),
        migrations.AddField(
            model_name='company',
            name='company_looking_to_hire_message',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
