# Generated by Django 3.0.8 on 2024-03-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210309_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='effective_price',
        ),
    ]
