# Generated by Django 3.0.8 on 2024-10-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210309_1948'),
        ('main', '0036_service_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='services',
            unique_together={('owner', 'service')},
        ),
    ]
