# Generated by Django 3.0.8 on 2024-11-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20241013_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Torn Feature', 'Tornfeature'), ('Company specials', 'Company'), ('Software', 'Software'), ('Atacking', 'Attacking'), ('Other', 'Other')], max_length=250),
        ),
    ]
