# Generated by Django 3.2.25 on 2025-03-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20241114_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
