# Generated by Django 3.2.25 on 2025-03-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20250310_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariation',
            name='is_saleable',
            field=models.BooleanField(default=False),
        ),
    ]
