# Generated by Django 3.2.25 on 2025-03-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_profile_api_key'),
        ('main', '0041_alter_itemvariation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
