# Generated by Django 3.2.25 on 2025-03-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_itemvariation_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariationbonuses',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
