# Generated by Django 3.2.25 on 2025-03-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_job_joblog_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='unique',
            field=models.BooleanField(default=False),
        ),
    ]
