# Generated by Django 3.2.25 on 2025-03-14 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_externallisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallisting',
            name='hits',
        ),
        migrations.AddField(
            model_name='externallisting',
            name='name',
            field=models.CharField(default='External Listing', max_length=250),
        ),
        migrations.AddField(
            model_name='externallisting',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='externallisting',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='ExternalListingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.BigIntegerField()),
                ('listing_type', models.CharField(max_length=250)),
                ('hidden', models.BooleanField(default=False)),
                ('external_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.externallisting')),
            ],
        ),
    ]
