# Generated by Django 3.2.25 on 2025-03-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20250314_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallisting',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
