# Generated by Django 3.2.25 on 2025-03-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_externallisting_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallistingitem',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
