# Generated by Django 3.2.25 on 2026-07-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_populate_effective_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='hidden_by_inactivity',
            field=models.BooleanField(default=False),
        ),
    ]
