# Generated by Django 3.2.25 on 2026-07-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_listing_hidden_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradereceipt',
            name='trade_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
