# Generated by Django 3.2.25 on 2026-08-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_add_trade_id_to_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bazaar_average',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='bazaar_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
