# Generated by Django 3.2.25 on 2026-08-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_item_bazaar_average'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('item_id__isnull', False)), fields=('item_id',), name='unique_non_null_item_id'),
        ),
    ]
