# Generated by Django 3.2.25 on 2026-08-08 22:07
# Manually edited to use CREATE INDEX CONCURRENTLY: itemtrade/tradereceipt can
# run into the millions of rows in production, and a plain AddIndex takes an
# ACCESS EXCLUSIVE lock for the duration of the index build.

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('main', '0055_bazaar_mv_changelog_entry'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='itemtrade',
            index=models.Index(fields=['owner'], name='itemtrade_owner_idx'),
        ),
        AddIndexConcurrently(
            model_name='itemtrade',
            index=models.Index(fields=['item'], name='itemtrade_item_idx'),
        ),
        AddIndexConcurrently(
            model_name='tradereceipt',
            index=models.Index(fields=['owner', 'seller'], name='tradereceipt_owner_seller_idx'),
        ),
        AddIndexConcurrently(
            model_name='tradereceipt',
            index=models.Index(fields=['seller'], name='tradereceipt_seller_idx'),
        ),
        AddIndexConcurrently(
            model_name='tradereceipt',
            index=models.Index(fields=['created_at'], name='tradereceipt_created_at_idx'),
        ),
        AddIndexConcurrently(
            model_name='tradereceipt',
            index=models.Index(fields=['trade_id'], name='tradereceipt_trade_id_idx'),
        ),
    ]
