# Generated by Django 3.2.25 on 2026-08-09 07:38
# Manually edited to use CREATE INDEX CONCURRENTLY, same reasoning as 0056:
# tradereceipt can run into the millions of rows in production.
#
# This expression index on UPPER(seller) is what makes `seller__iexact`
# (used to match a receipt's free-text seller name against the logged-in
# trader's Profile.name) index-able at all - Django compiles __iexact on
# Postgres to `UPPER(seller) = UPPER(value)`, which a plain btree index on
# `seller` cannot serve, forcing a sequential scan of the whole table.

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('main', '0056_receipt_search_indexes'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='tradereceipt',
            index=models.Index(django.db.models.functions.text.Upper('seller'), name='tradereceipt_seller_upper_idx'),
        ),
    ]
