# Generated by Django 3.2.25 on 2026-08-09 12:32
# Manually edited: AddField is a fast metadata-only change (nullable, no
# default) even on a huge table, but the index build needs CONCURRENTLY
# for the same reason as 0056/0057 - tradereceipt has 800k+ rows in
# production.

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('main', '0057_receipt_seller_upper_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradereceipt',
            name='total_amount',
            field=models.BigIntegerField(null=True),
        ),
        AddIndexConcurrently(
            model_name='tradereceipt',
            index=models.Index(fields=['total_amount'], name='tradereceipt_total_amount_idx'),
        ),
    ]
