# Generated by Django 4.2.30 on 2026-09-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_market_stats_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='event_discount_pct',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
