# Generated by Django 4.2.30 on 2026-09-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_listing_event_discount_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(db_index=True)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('torn_market_value', models.BigIntegerField(null=True)),
                ('itemmarket_price', models.BigIntegerField(null=True)),
                ('itemmarket_listings', models.JSONField(blank=True, null=True)),
                ('bazaar_average', models.BigIntegerField(null=True)),
                ('te_value', models.BigIntegerField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['item_id', 'captured_at'], name='main_itempr_item_id_666525_idx')],
            },
        ),
    ]
