# Generated by Django 4.2.30 on 2026-09-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_itempricelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lower_bound',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='upper_bound',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(check=models.Q(('lower_bound__isnull', True), ('upper_bound__isnull', True), ('lower_bound__lte', models.F('upper_bound')), _connector='OR'), name='listing_lower_bound_lte_upper_bound'),
        ),
    ]
